---
- hosts: nfs
  become: yes
  tasks:
  - name: install and update nfs package
    yum:
      name: nfs-utils*
      state: present
      update_cache: yes
  - name: creating a directory
    file:
      path: /home/ansible/nfs
      state: directory
      mode: 0755
  - name: exporting the directory
    template:
      src: templates/export.j2
      dest: /etc/exports
    notify:
    - restart nfs
  handlers:
    - name: restart nfs
      service:
        name: nfs-server
        state: restarted
  # client side configuration
- hosts: nfsclient
  become: yes
  tasks:
  - name: install nfs-utils
    yum:
      name: nfs-utils
      state: present
      update_cache: yes
    notify:
    - restart nfs
  - name: making director for mounting nfs_server
    file:
      path: /home/ansible/nfsclient
      state: directory
      mode: 0755
  - name: making fstab updated with mount point
    mount:
      path: /home/ansible/nfsclient
      src: 172.31.24.41:/home/ansible/nfs
      fstype: nfs
      opts: defaults
      state: mounted
  handlers:
    - name: restart nfs
      service:
        name: nfs-server
        state: restarted

  

    
  
    