---
# installing tomcat from 
# https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-16-04

- hosts: tomcat
  become: yes
  vars:
    folderpath: /opt/tomcat
  tasks:
  - name: updating packages
    apt:
      update_cache: yes
  - name: installing java development kit 
    apt:
      name: default-jdk
      state: present
  - name: install tomcat8
    apt:
      name: tomcat8
      state: present
  - name: start tomcat
    service:
      name: tomcat8
      state: started
  - name: templates
    template:
      src: templates/user-xml.j2
      dest: /var/lib/tomcat8/conf/tomcat-users.xml
  - name: restart again
    service:
      name: tomcat8
      state: restarted
      


  

