---
# installing tomcat from 
# https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-16-04

- hosts: tomcat
  become: yes
  vars:
    folderpath: /opt/tomcat
  tasks:
  - name: updating packages
    apt:
      update_cache: yes
  - name: installing java development kit 
    apt:
      name: default-jdk
      state: present
  - name: creating tomcat group
    group:
      name: tomcat
      state: present
  - name: adding tomcat user to tomcat group
    user:
      name: tomcat
      shell: /bin/false
      group: tomcat
  - name: install tomcat8
    apt:
      name: tomcat8
      state: present
  - name: giving tomcat group ownership over installation directory
    command: "chgrp -R tomcat /var/lib/"
  - name: giving read access to tomcat group to conf directory
    command: "chmod -R g+r /var/lib/tomcat8/conf"
    command: "chmod  g+x /var/lib/tomcat8/conf"
  - name: make tomcat user owner of folders
    command: "chown -R tomcat /var/lib/tomcat8/webapps/ /var/lib/tomcat8/work/ /var/lib/tomcat8/logs/"
  - name: templates
    template:
      src: templates/user-xml.j2
      dest: /var/lib/tomcat8/conf/tomcat-users.xml
  - name: restart again
    service:
      name: tomcat8
      state: restarted
      


  

