---
- hosts: all
  become: yes
  tasks: 
  - name: installing web server
    package:
      name: "{{ package_ name }}"
      state: present
  - name: update package manager
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: updating centos os
    yum:
      update_cache: yes
    when: ansible_os_family == "Redhat"