---
- hosts: all
  become: yes
  tasks: 
  - name: installing web server
    package:
      name: "{{ package_name }}"
      state: present
  - name: updating services
    service:
      name: "{{ package_name }}"
      state: started
  - name: update package manager
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: updating centos os
    yum:
      update_cache: yes
    when: ansible_os_family == "Redhat"
  - name: installing multiple packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ utilities }}"
     
  