---
- hosts: all
  become: yes
  tasks:
  - name: installing git on all the nodes
    apt:
      name: git
      state: present
- hosts: grpA
  become: yes
  tasks:
  - name: installing apache2 on grpA the nodes
    apt:
      name: apache2
      state: present
  - name: starting apache2 
    service:
      name: apache2
      state: started
- hosts: grpB
  become: yes
  tasks:
  - name: installing nginx on grpB
    apt:
      name: nginx
      state: present
  - name: starting nginx service
    service:
      name: nginx
      state: started
