---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: "create file"
    command: "touch /home/ubuntu/test.txt"
  - name: "store content"
    command: "echo hello > /home/ubuntu/test.txt"
  - name: "Display content"
    command: "cat /home/ubuntu/test.txt"
    register: file_content
  - name: "debug to print"
    debug:
      msg: "{{ file_content }}"