---
# configuring httpd web server on centos machies
# taken reference from 
# https://www.tecmint.com/install-apache-on-centos-7/
- hosts: all
  become: yes
  tasks:
  - name: installing httpd package
    yum:
      name: httpd
      state: present
      update_cache: yes
  - name: starting httpd server
    service:
      name: httpd
      state: started
  - name: enabling http in firewalld
  # make sure that by manually firewalld is present on the host machine
    firewalld:
      service: http
      permanent: true
      state: enabled
  