---
- hosts: all
  become: yes
  tasks: 
  - name: update apt packages
    apt:
      update_cache: yes
# Nodejs specific settings
- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/nodesetup
  tasks:
  - name: creating nodesetup directory
    file:
      path: "{{ folderpath }}"
      state: directory
      mode: 0755
  - name: download nodejs package setup
    command: "curl -sL https://deb.nodesource.com/setup_6.x -o {{ folderpath }}/nodesource_setup.sh"
  - name: execute download shellscript
    command: "sudo bash {{ folderpath }}/nodesource_setup.sh"
  - name: installing nodejs
    apt:
      name: nodejs
      state: present
  - name: copy the code
    template:
      src: "new/templates/hello.js.j2"
      dest: "{{ folderpath }}/hello.js.j2"
      
